spring.application.name=rabbitah-consumer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitah.queue.name=notification-queue
rabbitah.exchange.name=notification-exchange
rabbitah.routing.key=notification-routing-key

spring.main.web-application-type=none
