spring.application.name=rabbitah-producer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitah.exchange.name=notification-fanout-exchange
rabbitah.queue.order=order-queue
rabbitah.queue.email=email-queue

server.port=7890
